matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_AU
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  sources:
  - '!venv/**/*.md|**/*.md'
  default_encoding: utf-8

- name: HTML
  aspell:
    lang: en
    d: en_AU
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  sources:
  - '!venv/**/*.html|!output/**/*.html|**/*.html'
  default_encoding: utf-8
